### ISSUE TITLE
[Bug] In .NET 9 it doesn't seem to work anymore.

### ISSUE THREAD

**Issue by thepra** [Blazored/TextEditor#88]
**Describe the bug**
I'm trying to use this component in a .NET 9 based wasm based project and I get stuck at the most basic step:
`await quillHtml.LoadHTMLContent(HttpUtility.HtmlDecode(value))`
which throws an exception where the `quillElement` js object is null:

![Image](https://github.com/user-attachments/assets/1e3058a6-64cb-4881-98b1-ff9ec57f9f7f)

despite setting up everything by documentation.

**To Reproduce**
1. Start a new blazor wasm project
2. Add the nuget package
3. Setup the dependencies
4. Write the example code and invoke `LoadHTMLContent`

**Expected behavior**
Loading of the html working

**Screenshots**
Above ^

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Comment by ADefWebserver** [comment]
@thepra  I just updated [src/Blazored.TextEditor](https://github.com/Blazored/TextEditor/tree/main/src/Blazored.TextEditor). Can you please pull down the latest and see if that works for you?

**Comment by ADefWebserver** [comment]
Fixed with https://github.com/Blazored/TextEditor/commit/ffda95ec590ac235e47db12149e5caa20b6d46d3

**Comment by thepra** [comment]
Now the reference exist, but I still fail to load any HTML content, it just doesn't set up
![Image](https://github.com/user-attachments/assets/0ca14325-c766-49a0-90df-6b53d531e438)

**Comment by ADefWebserver** [comment]
Please install https://www.nuget.org/packages/Blazored.TextEditor/1.1.3 and clean your project and try again. I just tested it with Blazor Server 9 / Blazor WebAssembly 9 / and Blazor Server 8

**Comment by thepra** [comment]
Installed:

![Image](https://github.com/user-attachments/assets/f8c0a242-a7c4-4c00-ac45-f81c7dfb7ca3)

I'm using it like this and still having the `LoadHTMLContent` not doing the loading:
```
<div class="@SUtility.IfTrueThen(!isUpsertCommunicationTypeOpen, VConstants.HideClass)">
  <BlazoredTextEditor @ref="QuillHtml" Placeholder="<vuoto>">
  	<ToolbarContent>
  		<select class="ql-header">
  			<option selected=""></option>
  			<option value="1"></option>
  			<option value="2"></option>
  			<option value="3"></option>
  			<option value="4"></option>
  			<option value="5"></option>
  		</select>
  		<span class="ql-formats">
  			<button class="ql-bold"></button>
  			<button class="ql-italic"></button>
  			<button class="ql-underline"></button>
  			<button class="ql-strike"></button>
  		</span>
  		<span class="ql-formats">
  			<select class="ql-color"></select>
  			<select class="ql-background"></select>
  		</span>
  		<span class="ql-formats">
  			<button class="ql-list" value="ordered"></button>
  			<button class="ql-list" value="bullet"></button>
  		</span>
  		<span class="ql-formats">
  			<button class="ql-link"></button>
  		</span>
  	</ToolbarContent>
  </BlazoredTextEditor>
</div>
@code {
    bool isUpsertCommunicationTypeOpen;
    BlazoredTextEditor QuillHtml;
    async Task OpenCloseUpsertCommunicationType(ViewCommunicationType communicationType = default)
	{
		isUpsertCommunicationTypeOpen = communicationType != default || !isUpsertCommunicationTypeOpen;
		communicationTypeForm = communicationType?.ToForm() ?? new() { CampaignId = Campaign.Id };
		if (isUpsertCommunicationTypeOpen)
		{
			await QuillHtml.LoadHTMLContent($"<div>{communicationTypeForm.InfoDocText}</div>");
			StateHasChanged();
		}
	}
}
```

_So I'm wondering if quill isn't acting upon the `LoadHTMLContent` because it's inside a container that can be hidden at the time of the load._
Nope, tested out and even if the html is visible by default the loading doesn't happen on a button click in the interface that calls that `OpenCloseUpsertCommunicationType`
The following is the only warning I get from console at calling that content loading:

![Image](https://github.com/user-attachments/assets/46a9d080-fddb-4040-b4d6-7bda9e6361b6)

Am I doing something wrong with this setup?

**Comment by ADefWebserver** [comment]
Tell me if this code works for you, that will show that the component is set up correctly

```
@page "/"
@using Blazored.TextEditor
<PageTitle>Home</PageTitle>

<BlazoredTextEditor @ref="@QuillHtml1">
    <ToolbarContent>
        <select class="ql-header">
            <option selected=""></option>
            <option value="1"></option>
            <option value="2"></option>
            <option value="3"></option>
            <option value="4"></option>
            <option value="5"></option>
        </select>
        <span class="ql-formats">
            <button class="ql-bold"></button>
            <button class="ql-italic"></button>
            <button class="ql-underline"></button>
            <button class="ql-strike"></button>
        </span>
        <span class="ql-formats">
            <select class="ql-color"></select>
            <select class="ql-background"></select>
        </span>
        <span class="ql-formats">
            <button class="ql-list" value="ordered"></button>
            <button class="ql-list" value="bullet"></button>
        </span>
        <span class="ql-formats">
            <button class="ql-link"></button>
        </span>
    </ToolbarContent>
    <EditorContent>
        <h4>This Toolbar works with HTML</h4>
        <a href="http://BlazorHelpWebsite.com">
            BlazorHelpWebsite.com
        </a>
    </EditorContent>
</BlazoredTextEditor>
<br />
<button class="btn btn-primary"
        @onclick="GetHTML">
    Get HTML
</button>
<button class="btn btn-primary"
        @onclick="SetHTML">
    Set HTML
</button>
<br />
<BlazoredTextEditor @ref="@QuillHtml2">
    <ToolbarContent>
        <select class="ql-header">
            <option selected=""></option>
            <option value="1"></option>
            <option value="2"></option>
            <option value="3"></option>
            <option value="4"></option>
            <option value="5"></option>
        </select>
        <span class="ql-formats">
            <button class="ql-bold"></button>
            <button class="ql-italic"></button>
            <button class="ql-underline"></button>
            <button class="ql-strike"></button>
        </span>
        <span class="ql-formats">
            <select class="ql-color"></select>
            <select class="ql-background"></select>
        </span>
        <span class="ql-formats">
            <button class="ql-list" value="ordered"></button>
            <button class="ql-list" value="bullet"></button>
        </span>
        <span class="ql-formats">
            <button class="ql-link"></button>
        </span>
    </ToolbarContent>
    <EditorContent>
        <h4>This Toolbar works with HTML</h4>
        <a href="http://BlazorHelpWebsite.com">
            BlazorHelpWebsite.com
        </a>
    </EditorContent>
</BlazoredTextEditor>
<br />
<button class="btn btn-primary"
        @onclick="GetHTML2">
    Get HTML
</button>
<button class="btn btn-primary"
        @onclick="SetHTML2">
    Set HTML
</button>
<br />
<div>
    <br />
    @((MarkupString)QuillHTMLContent)
    @QuillHTMLContent
</div>
@code {

    BlazoredTextEditor QuillHtml1;
    BlazoredTextEditor QuillHtml2;
    string QuillHTMLContent;

    public async Task GetHTML()
    {
        QuillHTMLContent = await this.QuillHtml1.GetHTML();
    }

    public async Task SetHTML()
    {
        string QuillContent =
            @"<a href='http://BlazorHelpWebsite.com/'>" +
            "<img src='images/BlazorHelpWebsite.gif' /></a>";

        await this.QuillHtml1.LoadHTMLContent(QuillContent);
    }

    public async Task GetHTML2()
    {
        QuillHTMLContent = await this.QuillHtml2.GetHTML();
    }

    public async Task SetHTML2()
    {
        string QuillContent =
            @"<a href='http://BlazorHelpWebsite.com/'>" +
            "<img src='images/BlazorHelpWebsite.gif' /></a>";

        await this.QuillHtml2.LoadHTMLContent(QuillContent);
    }
}
```

**Comment by thepra** [comment]
I tested your 2 extra examples(1 mine + 2 examples), crazy thing is that they both work, after changing the type of the buttons to `button` because I'm in a `EditForm` so they weren't triggered correctly. But the first one (that I kept in the code didn't work. 
The craziest thing is that I also called the `LoadHTMLContent` from withing the same `OpenCloseUpsertCommunicationType` from before and they did load the content correctly for the 2 examples! but the first one(mine) is still rendering the initial `<h4>This Toolbar works with HTML</h4>`, and looking at the quill logs there's something fishy going on because I see this steps:
1. Sets the editor value to the correct HTML
2. Sets the editor value to the initial `<h4>This Toolbar works with HTML</h4>`
3. Sets the editor value to the correct HTML
4. Sets the editor value to the initial `<h4>This Toolbar works with HTML</h4>`

Logs:

![Image](https://github.com/user-attachments/assets/0aa13c55-6f1f-40b1-aa83-12ec6851a016)

Am I going nuts by calling the `LoadHTMLContent` once?

And now the final main finding, putting that `<BlazoredTextEditor>` **outside** the `<EditForm>` with an `OnValidSubmit` function(empty) + `<DataAnnotationsValidator/>`  makes the `<BlazoredTextEditor>` work normally.

So I guess having this component inside and `EditForm` is triggering quills to make incorrect calls, can you confirm that with such setup you get this wrong behaviour?

**Comment by ADefWebserver** [comment]
This sounds normal because the Quill JavaScript will easily break if Blazor selectively hides things. This can be divs Edit Form controls ect. [Radzen ](https://razor.radzen.com/html-editor) has a text editor control that may behave more in the way you desire.
